import type { LocaleKey } from "@/types/localeProps.interface";

/**
 * Reviews from the Sanad Care Google Business Profile.
 *
 * These are copied by hand from the profile rather than pulled through the
 * Places API, which needs billing enabled. Because they are copied, they must
 * be reproduced **verbatim**: no rewriting, no trimming a review down to the
 * good half, no fixing anyone's grammar or spelling. The text belongs to the
 * reviewer, and "Sanade Care" below is the reviewer's own typo, left as
 * written.
 *
 * The author's name and star rating are shown on every card, and the section
 * links back to the profile, which is what makes republishing these defensible.
 */
export interface Review {
  id: string;
  author: string;
  rating: 1 | 2 | 3 | 4 | 5;
  text: string;
  /**
   * ISO date (YYYY-MM-DD).
   *
   * Google shows relative dates ("2 days ago"), which would read as nonsense a
   * month later, so these are the equivalent calendar dates at the time of
   * capture. Month and year are what get displayed, so they do not claim more
   * precision than the source did.
   */
  date: string;
  /** Set only when the review is written in a different language from the page. */
  language?: LocaleKey;
}

/** The "leave us a review" short link, generated by Google Business Profile. */
export const GOOGLE_REVIEW_URL = "https://g.page/r/CVnCSahJZRA3EAE/review";

/**
 * Where visitors can read every review.
 *
 * The canonical Google Maps URL for the profile, resolved from the short link
 * `maps.app.goo.gl/6x1FqBosKG8EFDK88` and keyed by the place's CID, so it stays
 * stable. No API key involved.
 */
export const GOOGLE_PROFILE_URL = "https://www.google.com/maps?cid=3967782638743831129";

/** The profile's coordinates, taken from the resolved Maps URL. */
export const GOOGLE_GEO = { latitude: 31.6450142, longitude: -8.0122298 };

/**
 * The rating and review count exactly as the Google profile shows them.
 *
 * Kept separate from the array on purpose: the average of the reviews we
 * display is not the profile's rating, and a number derived from a selection
 * would misrepresent it. Update this from the profile when it changes.
 */
export const GOOGLE_RATING: { value: number; count: number } | null = {
  value: 5,
  count: 7,
};

/** In the order the profile lists them: newest first. */
export const REVIEWS: Review[] = [
  {
    id: "warda-zahid-khan",
    author: "Warda Zahid Khan",
    rating: 5,
    date: "2026-10-05",
    text: "As a tourist visiting from America, I came back to Marrakech after summiting Toubkal with very painful toes and blisters under both nails. I was worried, especially with a Sahara desert trip coming up in 2 days. Anas from SANAD Care came to our riad, examined both toes very thoroughly, and took the time to explain what he saw. He honestly told me the blisters didn't need to be drained, instead of doing a procedure I didn't need, and gave me cleaning kits to take with me just in case. Professional, kind, and trustworthy. I will now go with peace of mind, ready for the dunes. Highly recommend Anas and SANAD Care to any traveler in Marrakech who needs a nurse!",
  },
  {
    id: "david-malorano",
    author: "David Malorano",
    rating: 5,
    date: "2026-10-04",
    language: "fr",
    text: "Nous étions en vacances et notre fils devait se faire enlever des points de sutures avant notre retour en Suisse. L'infirmier a été super ! Efficace et professionnel. Nous étions très satisfaits !",
  },
  {
    id: "phil-meyer",
    author: "Phil Meyer",
    rating: 5,
    date: "2026-10-04",
    text: "I'm an American tourist in Marrakech that needed staples removed from my scalp. Setting up the appointment was easy, and Anas, the nurse, was skilled, kind and had a good sense of humor. He came to me in my riad and the fee was very reasonable. Highly recommend.",
  },
  {
    id: "rihab-rinouch",
    author: "rihab rinouch",
    rating: 5,
    date: "2026-09-08",
    language: "fr",
    text: "Très bonne expérience avec Sanade Care. L'équipe est professionnelle, à l'écoute et vraiment disponible. J'ai apprécié leur sérieux, leur gentillesse et la qualité de l'accompagnement. Tout s'est très bien passé du début à la fin. Je recommande sans hésiter !",
  },
  {
    id: "ismail-et-talbi",
    author: "Ismail Et-talbi",
    rating: 5,
    date: "2026-07-28",
    language: "fr",
    text: "Service impeccable ! L'infirmière est venue à domicile pour une prise de sang chez ma mère, ponctuelle et très professionnelle. Résultats reçus en moins de 24h avec un suivi WhatsApp très rassurant. Je recommande vivement Sanad Care pour toute famille qui cherche des soins de qualité à Marrakech",
  },
  {
    id: "hachdi-ech-chafi",
    author: "Hachdi Ech Chafi",
    rating: 5,
    date: "2026-07-07",
    text: "Salam nass tbankalah 3andhom tawasol mazyan o kay3tiwk lwa9t lah isahal 3lihom",
  },
  {
    id: "kholoud-kraba",
    author: "Kholoud Kraba",
    rating: 5,
    date: "2026-07-07",
    language: "fr",
    text: "Grâce à Sanad Care, ma mère n'a plus besoin de se déplacer pour ses soins. Un vrai soulagement pour toute la famille",
  },
];
